noticed this bug on away messages for users not in shared channels:
java.lang.NullPointerException: Cannot invoke "org.pircbotx.User.setAwayMessage(String)" because "sourceUser" is null
at org.pircbotx.InputParser.processCommand(InputParser.java:707)
at org.pircbotx.InputParser.handleLine(InputParser.java:430)
at org.pircbotx.PircBotX.processNextLine(PircBotX.java:416)
at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:363)
at org.pircbotx.PircBotX.connect(PircBotX.java:351)
at org.pircbotx.PircBotX.startBot(PircBotX.java:179)